### ISSUE TITLE
New Variable Attribute Requirements

### ISSUE THREAD

**Issue by Alrobbertz** [IHDE-Alliance/ISTP_metadata#4]
It seems like there are new variable metadata attributes that are marked required in these documents that are not outlined in the current [Variable Attributes Guide on SPDF](https://spdf.gsfc.nasa.gov/istp_guide/vattributes.html#variable).

- REPRESENTATION_i: Pointer to a support variable that gives the representation (['x','y','z'] for Cartesian; ['r','p','t'] for spherical polar; ['r','p','z'] for cylindrical polar) of the ith dimension of the variable.
- SIZES: Essential for any variable that has more than one element, such as arrays and vectors.
- TENSOR_FRAME: Contains the frame of a tensor.
- TENSOR_ORDER: Contains the rank or order of a tensor, i.e. 1 for a vector, 2 for a 3x3 tensor.
- VALUE_TYPE: This identifies the data type and is necessary for conversion from the ascii entry.

Are these truly required for current missions? If not, when will they become required for new CDF data to be uploaded to SPDF?

**Comment by candeynasa** [comment]
No, not required for SPDF (although may be required for some missions).  But that's clearly a mistake in our chart.  We developed this markdown version, but haven't reviewed it yet.  We shouldn't have marked it as 1.0.  We'll get this fixed.
